### PR TITLE
Fixed mod arrays written on bank 0

### PR DESCRIPTION
**Pull request by Zal0**
The only important change is line 922 where the const unsigned char * is changed to be exported as const unsigned char *const ensuring all the data is exported in the same bank
The other changes where needed because of the version of gcc I was using forcing me to declare all vars at the begginning of a function

### CODE REVIEW

**Review by AntonioND — COMMENTED** [review]
Well, as far as I can see the only real  change is the addition of a "const". Could you reduce the patch to that? The other reorganization of variables is superfluous and makes it difficult to see the real changes (and it's inconsistent, you use tabs and spaces for indentation). The exe file is unnecessary too.

If you really want to put the variables at the beginning of the functions, do it in another patch on top of the "const" patch and I'll merge the pull request with both of them.

**Comment by AntonioND** [comment]
Sorry, that's because of the visualization of GitHub, now I see there are 2 commits. Just fix the inconsistent indentation.

**Comment by AntonioND** [comment]
Actually, who cares about that? This is just the legacy version.

**Comment by Zal0** [comment]
Oh, thanks! I was going to fix it. That const was the only thing needed

**Pull request merged**
